name: dagger
on:
  push:
    branches: [main]

jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      -
        name: Call Dagger Function
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: publish --source=.
